### ISSUE TITLE
CM108 GPIO support for PTT and remote channel steering + LPT support for RCS

### ISSUE THREAD

**Issue by buhalo1** [W3AXL/RadioConsole2#2]
Analog radios, such as GM300 Professional series (Waris) or older Radius series, support remote channel steering by manipulating 4 or 6 pins of the accessory connector.
GM300 Professional (Waris) series also supports SB9600, but older radios only support RCS functionality.
It would be very useful to be able to control such radios as well. To do this, it is necessary to be able to control the CM108 GPIO outputs and also, as an alternative, the D0-D7 pins of the LPT port.
At the same time, it is desirable to be able to assign channel names to radios controlled in this way, since the radios themselves do not support alphanumeric names, as well as the ability to transfer them to the console..

Perhaps this project will help add SB9600 support for GM300 Professional (Waris) series to your project.
https://github.com/satcom-uhf/MotoRoller

It would also be very useful to be able to patch a controlled radio to the ASL RoIP network from the daemon side, so that the patch remains even when the client is disconnected.
Connecting to a local RoIP network node is possible as a USRP client (https://github.com/DVSwitch/USRP_Client) or as an IAXRPT client, as implemented in Droidstar (https://github.com/nostar/DroidStar).
I believe that the second option is more difficult to implement but allows for more flexible switching of communication lines.
It would also be very useful to be able to patch to the RoIP and to the PBX from client side using SIP or/and IAXRPT.
Thank you.

**Comment by W3AXL** [comment]
There's a lot of requests here. I'm all for implementing new features, but I'm only one person. I'd recommend you create new feature requests for each feature individually - helps to track things easier and gives me more manageable bites to work on.
